#!/usr/bin/env sh
#
#
set -u -e -o pipefail
cd "$( dirname "$(realpath "$0")" )/.."
THIS_DIR="$PWD"


for x in Spec String ; do
  echo ""
  echo "======== ${x} ======================"
  deno run --allow-net=localhost --allow-read=tmp --allow-write=tmp spec/${x}.ts
done # for
echo ""
