#!/usr/bin/env sh
#
#
set -u -e -o pipefail
cd "$( dirname "$(realpath "$0")" )/.."
THIS_DIR="$PWD"


THE_FILENAME="$@"

case "$THE_FILENAME" in
  "")
    for x in Spec String ; do
      echo ""
      echo "======== ${x} ======================"
      sh/spec ${x}
    done # for
    echo ""
    ;;
  *)
    deno run --allow-net=localhost --allow-read=tmp --allow-write=tmp spec/${THE_FILENAME}.ts
    ;;
esac
