#!/usr/bin/env bash
#
#
set -u -e -o pipefail

export IS_TEST="yes"
export FORCE_COLOR=true

case "$@" in
  "")
    names="main migrate prune"
    ;;
  *)
    names=$*
    ;;
esac

for x in ${names}
do
  file_name="spec/${x}.mjs"
  secrets FAUNA_JS node "${file_name}" \
    || ( echo -e "\n !!! \e[31m FAILED:\e[m ${file_name} !!!\n" && exit 1 )
  echo -e "\n ==== \e[32m PASSED:\e[m ${file_name}  ====\n"
done
