#!/usr/bin/env bash

set -u -e -o pipefail

find ./bin ./src -type f -name '*.ts' | while IFS= read -r x ; do
echo "=== deno cache --reload $x"
deno cache --reload "$x"
done # for

if test -d node_modules ; then
  npm update
fi # if
