#!/usr/bin/env sh
#
#
set -u -e -o pipefail

mkdir -p tmp/spec

source $HOME/secrets/fauna.miniuni_dev_key.sh

IS_TEST="yes" deno run \
  --allow-run=echo,node,uptime \
  --allow-env="IS_TEST,NO_COLOR,FAUNA_SECRET_TEST_A,FAUNA_SECRET_TEST_B" \
  --allow-net=deno.land,raw.githubusercontent.com \
  --allow-read="./,tmp/spec" \
  --allow-write="tmp/spec" \
  spec/main.ts $@
